FROM python:3.10.11-slim-bullseye

WORKDIR /app
COPY ./clientResponder.py .
COPY ./client_producer.py .

RUN python -m pip install flask
RUN python -m pip install flask_cors
RUN python -m pip install pika
RUN python -m pip install mysql-connector-python

EXPOSE 5800/tcp

CMD python -m flask --app clientResponder run --host=0.0.0.0 -p 5800
